### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'model')

### ISSUE THREAD

**Issue by Discobotdevlolhehe** [Uo1428/AnotherJourney#1]
✯ |=== [AntiCrash] | [unhandledRejection] | [start] ====| ✯
TypeError: Cannot read properties of undefined (reading 'model')
    at Object.get (file:///home/runner/FinishedRetreat/node_modules/node-replicate/index.js:21:70)
    at Object.run (file:///home/runner/FinishedRetreat/node_modules/node-replicate/index.js:14:28)
✯ |=== [AntiCrash] | [unhandledRejection] | [end] ===| ✯

pls help

**Comment by Discobotdevlolhehe** [comment]
@Uo1428

**Comment by Noob02lol** [comment]
Same

**Comment by Uo1428** [comment]
to fix this -> https://www.youtube.com/watch?v=T3aQ58JLVXM
